/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedCoachUsersRouteImport } from './routes/_authenticated/coach/users'
import { Route as AuthenticatedCoachNutritionRouteImport } from './routes/_authenticated/coach/nutrition'
import { Route as AuthenticatedCoachAssignmentsRouteImport } from './routes/_authenticated/coach/assignments'
import { Route as AuthenticatedCoachAnnouncementsRouteImport } from './routes/_authenticated/coach/announcements'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app/support'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/app/subscription'
import { Route as AuthenticatedAppNutritionRouteImport } from './routes/_authenticated/app/nutrition'
import { Route as AuthenticatedCoachRoutinesIndexRouteImport } from './routes/_authenticated/coach/routines/index'
import { Route as AuthenticatedAppTrainingIndexRouteImport } from './routes/_authenticated/app/training/index'
import { Route as AuthenticatedCoachRoutinesIdRouteImport } from './routes/_authenticated/coach/routines/$id'
import { Route as AuthenticatedAppTrainingIdRouteImport } from './routes/_authenticated/app/training/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedCoachUsersRoute = AuthenticatedCoachUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedCoachNutritionRoute =
  AuthenticatedCoachNutritionRouteImport.update({
    id: '/nutrition',
    path: '/nutrition',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachAssignmentsRoute =
  AuthenticatedCoachAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachAnnouncementsRoute =
  AuthenticatedCoachAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNutritionRoute =
  AuthenticatedAppNutritionRouteImport.update({
    id: '/nutrition',
    path: '/nutrition',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedCoachRoutinesIndexRoute =
  AuthenticatedCoachRoutinesIndexRouteImport.update({
    id: '/routines/',
    path: '/routines/',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAppTrainingIndexRoute =
  AuthenticatedAppTrainingIndexRouteImport.update({
    id: '/training/',
    path: '/training/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedCoachRoutinesIdRoute =
  AuthenticatedCoachRoutinesIdRouteImport.update({
    id: '/routines/$id',
    path: '/routines/$id',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAppTrainingIdRoute =
  AuthenticatedAppTrainingIdRouteImport.update({
    id: '/training/$id',
    path: '/training/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/app/nutrition': typeof AuthenticatedAppNutritionRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/coach/announcements': typeof AuthenticatedCoachAnnouncementsRoute
  '/coach/assignments': typeof AuthenticatedCoachAssignmentsRoute
  '/coach/nutrition': typeof AuthenticatedCoachNutritionRoute
  '/coach/users': typeof AuthenticatedCoachUsersRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/app/training/$id': typeof AuthenticatedAppTrainingIdRoute
  '/coach/routines/$id': typeof AuthenticatedCoachRoutinesIdRoute
  '/app/training/': typeof AuthenticatedAppTrainingIndexRoute
  '/coach/routines/': typeof AuthenticatedCoachRoutinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/nutrition': typeof AuthenticatedAppNutritionRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/coach/announcements': typeof AuthenticatedCoachAnnouncementsRoute
  '/coach/assignments': typeof AuthenticatedCoachAssignmentsRoute
  '/coach/nutrition': typeof AuthenticatedCoachNutritionRoute
  '/coach/users': typeof AuthenticatedCoachUsersRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/app/training/$id': typeof AuthenticatedAppTrainingIdRoute
  '/coach/routines/$id': typeof AuthenticatedCoachRoutinesIdRoute
  '/app/training': typeof AuthenticatedAppTrainingIndexRoute
  '/coach/routines': typeof AuthenticatedCoachRoutinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/app/nutrition': typeof AuthenticatedAppNutritionRoute
  '/_authenticated/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/coach/announcements': typeof AuthenticatedCoachAnnouncementsRoute
  '/_authenticated/coach/assignments': typeof AuthenticatedCoachAssignmentsRoute
  '/_authenticated/coach/nutrition': typeof AuthenticatedCoachNutritionRoute
  '/_authenticated/coach/users': typeof AuthenticatedCoachUsersRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/app/training/$id': typeof AuthenticatedAppTrainingIdRoute
  '/_authenticated/coach/routines/$id': typeof AuthenticatedCoachRoutinesIdRoute
  '/_authenticated/app/training/': typeof AuthenticatedAppTrainingIndexRoute
  '/_authenticated/coach/routines/': typeof AuthenticatedCoachRoutinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app'
    | '/coach'
    | '/app/nutrition'
    | '/app/subscription'
    | '/app/support'
    | '/coach/announcements'
    | '/coach/assignments'
    | '/coach/nutrition'
    | '/coach/users'
    | '/app/'
    | '/coach/'
    | '/app/training/$id'
    | '/coach/routines/$id'
    | '/app/training/'
    | '/coach/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/nutrition'
    | '/app/subscription'
    | '/app/support'
    | '/coach/announcements'
    | '/coach/assignments'
    | '/coach/nutrition'
    | '/coach/users'
    | '/app'
    | '/coach'
    | '/app/training/$id'
    | '/coach/routines/$id'
    | '/app/training'
    | '/coach/routines'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/coach'
    | '/_authenticated/app/nutrition'
    | '/_authenticated/app/subscription'
    | '/_authenticated/app/support'
    | '/_authenticated/coach/announcements'
    | '/_authenticated/coach/assignments'
    | '/_authenticated/coach/nutrition'
    | '/_authenticated/coach/users'
    | '/_authenticated/app/'
    | '/_authenticated/coach/'
    | '/_authenticated/app/training/$id'
    | '/_authenticated/coach/routines/$id'
    | '/_authenticated/app/training/'
    | '/_authenticated/coach/routines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/coach/users': {
      id: '/_authenticated/coach/users'
      path: '/users'
      fullPath: '/coach/users'
      preLoaderRoute: typeof AuthenticatedCoachUsersRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/nutrition': {
      id: '/_authenticated/coach/nutrition'
      path: '/nutrition'
      fullPath: '/coach/nutrition'
      preLoaderRoute: typeof AuthenticatedCoachNutritionRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/assignments': {
      id: '/_authenticated/coach/assignments'
      path: '/assignments'
      fullPath: '/coach/assignments'
      preLoaderRoute: typeof AuthenticatedCoachAssignmentsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/announcements': {
      id: '/_authenticated/coach/announcements'
      path: '/announcements'
      fullPath: '/coach/announcements'
      preLoaderRoute: typeof AuthenticatedCoachAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/subscription': {
      id: '/_authenticated/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nutrition': {
      id: '/_authenticated/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AuthenticatedAppNutritionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/coach/routines/': {
      id: '/_authenticated/coach/routines/'
      path: '/routines'
      fullPath: '/coach/routines/'
      preLoaderRoute: typeof AuthenticatedCoachRoutinesIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/app/training/': {
      id: '/_authenticated/app/training/'
      path: '/training'
      fullPath: '/app/training/'
      preLoaderRoute: typeof AuthenticatedAppTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/coach/routines/$id': {
      id: '/_authenticated/coach/routines/$id'
      path: '/routines/$id'
      fullPath: '/coach/routines/$id'
      preLoaderRoute: typeof AuthenticatedCoachRoutinesIdRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/app/training/$id': {
      id: '/_authenticated/app/training/$id'
      path: '/training/$id'
      fullPath: '/app/training/$id'
      preLoaderRoute: typeof AuthenticatedAppTrainingIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppNutritionRoute: typeof AuthenticatedAppNutritionRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppTrainingIdRoute: typeof AuthenticatedAppTrainingIdRoute
  AuthenticatedAppTrainingIndexRoute: typeof AuthenticatedAppTrainingIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppNutritionRoute: AuthenticatedAppNutritionRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppTrainingIdRoute: AuthenticatedAppTrainingIdRoute,
  AuthenticatedAppTrainingIndexRoute: AuthenticatedAppTrainingIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachAnnouncementsRoute: typeof AuthenticatedCoachAnnouncementsRoute
  AuthenticatedCoachAssignmentsRoute: typeof AuthenticatedCoachAssignmentsRoute
  AuthenticatedCoachNutritionRoute: typeof AuthenticatedCoachNutritionRoute
  AuthenticatedCoachUsersRoute: typeof AuthenticatedCoachUsersRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
  AuthenticatedCoachRoutinesIdRoute: typeof AuthenticatedCoachRoutinesIdRoute
  AuthenticatedCoachRoutinesIndexRoute: typeof AuthenticatedCoachRoutinesIndexRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachAnnouncementsRoute: AuthenticatedCoachAnnouncementsRoute,
  AuthenticatedCoachAssignmentsRoute: AuthenticatedCoachAssignmentsRoute,
  AuthenticatedCoachNutritionRoute: AuthenticatedCoachNutritionRoute,
  AuthenticatedCoachUsersRoute: AuthenticatedCoachUsersRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
  AuthenticatedCoachRoutinesIdRoute: AuthenticatedCoachRoutinesIdRoute,
  AuthenticatedCoachRoutinesIndexRoute: AuthenticatedCoachRoutinesIndexRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
